codefordurham/school-navigator

- frontend/app/controllers/schoolsMap.js
- frontend/app/directives/MapDirectives.js
- frontend/app/templates/map.html
- frontend/css/index.css
- frontend/index.html
- schools/models.py
- schools/serializers.py
First pass at color-coding the schools. You can demo this branch on https://schools.codefordurham.com/
> School colors

- schools/migrations/0007_add_desc_photo.py
- schools/models.py
> Adds photo and description field to schools

- frontend/app/directives/MapDirectives.js
This commit fixes issue 78 with regard to house and school icons being represented in places slightly off from the actual map location.
> 78 map icon fix

- frontend/app/templates/nav-menu.html
We have no copy for this page so we have decided to remove it from now
> [fixes #96] Removes school list page

- frontend/app/app.js
- frontend/app/templates/search.html
Assumes that grade_min and grade_max are -1 .. 12
preK = -1
K = 0
1 = 1
...
12 = 12
> [fixes #104] gradeString filter to show K

- frontend/app/templates/search.html
This commit fixes the problem that borders are shown regardless of whether the school is hidden.
> Hide border when hiding school

- schools/management/commands/loadschools.py
Thanks @jwaldrep for finding this while researching #145
> Fix missing reference to name

- frontend/app/app.js
- frontend/app/templates/map.html
- frontend/app/templates/search.html
- frontend/css/index.css
Color coded borders and a legend to signify different types of districts
> Issue 191 

- frontend/app/app.js
- frontend/app/templates/details.html
@victor-rocha please take a look and see if this is a good approach.
-  check security on untrusted html input from survey form
> Adds line break filter.

- frontend/app/templates/search.html
> #262 - removed extra year-round class

- school_navigator/templates/survey_email_charter.txt
- school_navigator/templates/survey_email_dps.txt
> Email template 333

- frontend/app/templates/search.html
> Fixes #259 Link full profiles to mini profiles in map view

- school_navigator/templates/survey_form.html
> Change language in survey of year-round school from "TRUE/FALSE" to "Yes/No" Issue #347

- docs/dev-setup.rst
resolves #363 
The suggested command in the docs was giving me errors -- @JonathanFrederick had the same problem using the backend setup and we resolved it with using this command. `pip install -r $PWD/requirements/dev.txt`
> changes command for backend setup of requirements

- schools/models.py
adds help text to show that emails sent to a principal may also reach their Superintendent
resolves #339
> Issue#339/principal super email

- frontend/app/templates/details-new.html
Removed 'Sample DPS School' text from live profiles
> Fix school names on profiles

- frontend/css/index.css
@vrocha on the school profile page, I replaced the middle school blue with a neutral gray (until we decide how/if to deal with color coding school levels).
> School profile page: replaced middle school blue with a neutral gray

- frontend/css/index.css
> Add drop shadow to navbar

- frontend/css/index.css
Per recommendation from usability testing, removed down arrows from the tabs
> Removed down arrow from on-page tabs

- frontend/css/index.css
Font size and line height increased
> Increased font size and line height

- frontend/app/templates/about.html
> Fixed Typo

- frontend/app/templates/details-new.html
- frontend/css/index.css
Tweaked a few things on the school profile page to improve appearance and information architecture
> School profile page tweaks

- frontend/app/templates/details-new.html
per issue #383 adding linky to the details-new.html template at various points where there are links that were not rendered.
> updated details-new page with linky in appropriate places

- frontend/css/index.css
minor CSS fix to restrict overflow found with issue #428
> adding css to limit overflow in articles

- school_navigator/templates/survey_email_dps.txt
updated dps email (still need to make those changes to charter and dps email needs some additional edits as well)
> Removed Additional FYIs text from DPS survey email template

- school_navigator/templates/survey_email_charter.txt
- school_navigator/templates/survey_email_dps.txt
> update survey email for 1 week extension

- schools/models.py
Hold off on merging this until surveys close (after ~Jan 16th 2018).
> Fixes #443, #384. Timezone aware due date fixes

- school_navigator/templates/survey_email_charter.txt
- school_navigator/templates/survey_email_dps.txt
- schools/forms.py
- schools/models.py
* Update percent complete to only include fields that are relevant
* Clear feedback field between survey creations so that new feedback can be shared with us.
> Update percent complete & clear feedback field
